version: '3.8'

services:
 minio:
   image: minio/minio:latest
   container_name: minio
   hostname: minio
   ports:
     - "9000:9000"      # API port
     - "9001:9001"      # Console port
   command: server /data --console-address ":9001"
   environment:
     - MINIO_ROOT_USER=username
     - MINIO_ROOT_PASSWORD=password
   healthcheck:
     test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
     interval: 30s
     timeout: 20s
     retries: 3


 minio-setup:
   image: minio/mc:latest
   container_name: minio-setup
   depends_on:
     minio:
       condition: service_healthy
   entrypoint: >
     /bin/sh -c "
     sleep 5;
     mc alias set myminio http://minio:9000 username password;
     mc mb myminio/trellis;
     echo 'Bucket trellis created successfully';
     "